language: cpp

# precise gcc doesn't have c++11 support

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: clang
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: precise
      compiler: clang
    - os: osx
      osx_image: xcode7.2
    - os: osx
      compiler: clang
    - os: osx
      compiler: gcc

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

before_script:
  - ./autogen.sh

script:
  - ./configure && make