language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y;
  - sudo apt-get update;
  - sudo apt-get install cmake cmake-data -y;

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

script:
  - cmake -G "Unix Makefiles"
    