language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: precise
    - os: osx
      osx_image: xcode7.2

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

before_script:
  - ./autogen.sh