language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - george-edison55/cmake-3.x
    packages:
      - libcurl4-openssl-dev
      - cmake
      - cmake-data

script:
  - cmake -G "Unix Makefiles"
    